# Generated by Django 6.0.2 on 2026-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('image', models.URLField(max_length=500)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('fulldesc', models.TextField()),
                ('photos', models.JSONField(default=list)),
                ('desc', models.JSONField(default=list)),
                ('variants', models.JSONField(default=list)),
                ('availableSizes', models.JSONField(default=list)),
                ('models_name', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('all', 'Все'), ('new', 'Новинки'), ('hit', 'Хиты')], default='all')),
                ('gender', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300)),
            ],
        ),
    ]
